name: Archicad Add-On Windows Build Manual

on: 
  workflow_dispatch:

jobs:
  build_win_ac26:
    runs-on: [ windows-2019 ]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Download Development Kit
      run: python archicad-addon/Tools/download_and_unzip.py ${{ secrets.WIN_DEVKIT_AC26 }} archicad-addon/Build
    - name: Generate Project
      run: cmake -B archicad-addon/Build/AC26 -G "Visual Studio 17 2022" -A "x64" -T "v142" -DAC_API_DEVKIT_DIR="archicad-addon/Build/API Development Kit 26.3000" archicad-addon
    - name: Build Debug
      run: cmake --build archicad-addon/Build/AC26 --config Debug
    - name: Build RelWithDebInfo
      run: cmake --build archicad-addon/Build/AC26 --config RelWithDebInfo
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Tapir Add-On AC26 Win
        path: archicad-addon/Build/AC26/RelWithDebInfo/TapirAddOn_AC26_Win.apx
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: ncipollo/release-action@v1
      with:
        artifacts: archicad-addon/Build/AC26/RelWithDebInfo/TapirAddOn_AC26_Win.apx
        draft: true
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
